FROM docker.elastic.co/kibana/kibana:6.3.2
RUN kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v0.7.1/enhanced-table-0.7.1_6.3.2.zip
# RUN kibana-plugin install x-pack
# RUN kibana-plugin install https://github.com/ppadovani/KibanaNestedSupportPlugin/releases/download/6.2.1-1.0.2/nested-fields-support-6.2.1-1.0.2.zip
# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
