FROM docker.elastic.co/kibana/kibana:7.4.0
RUN kibana-plugin install https://github.com/fatmali/kibana-enhanced-table/releases/download/1.5.1/enhanced-table-1.5.1_7.4.0.zip
RUN kibana-plugin install https://github.com/fatmali/kibana-iframe-communicator-plugin/releases/download/v1.0.0/kibana-iframe-communicator-plugin-1.0.0_7.4.0.zip
RUN kibana-plugin install https://github.com/fatmali/patient-nav-formatter/releases/download/v1.0.0/patient-nav-1.0.0_7.4.0.zip
