FROM docker.elastic.co/elasticsearch/elasticsearch:7.4.0
#RUN ./bin/elasticsearch-plugin install https://github.com/NLPchina/elasticsearch-sql/releases/download/6.1.0.0/elasticsearch-sql-6.1.0.0.zip
#RUN ./bin/elasticsearch-plugin install x-pack
#RUN chown /usr/share/elasticsearch/config/x-pack
#RUN ./bin/x-pack/users useradd my_admin -p mypassword -r superuser

