# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash:6.3.2
# USER root
# RUN mkdir /usr/share/last_run &&\
#    chown logstash:logstash /usr/share/last_run
# USER logstash
# RUN logstash-plugin install x-pack
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
